<?php
$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
?>
<!-- This page overrides /application/view/omeka/site/item/show.phtml -->
<?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 2); ?>
<div class="blocks">
    <h3><?php echo $translate('Item'); ?></h3>
    <?php $this->trigger('view.show.before'); ?>
    <?php echo $this->resourcePageBlocks($item)->getBlocks(); ?>
</div>
<?php $this->trigger('view.show.after'); ?>
